# Generated by Django 2.1 on 2018-08-28 23:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('ext_no', models.CharField(blank=True, max_length=150, null=True)),
                ('int_no', models.CharField(blank=True, max_length=30, null=True)),
                ('colony', models.CharField(blank=True, max_length=150, null=True)),
                ('municipality', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('country', models.CharField(default='México', max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=11, null=True)),
                ('rfc', models.CharField(db_index=True, max_length=15)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=250)),
                ('bank_account_no', models.CharField(max_length=21)),
                ('clabe', models.CharField(max_length=23)),
                ('bank_name', models.CharField(max_length=100)),
                ('telephone1', models.CharField(max_length=16)),
                ('telephone2', models.CharField(blank=True, max_length=16)),
                ('telephone3', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=130)),
                ('contact_name', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('credit', models.BooleanField(default=False)),
                ('credit_days', models.PositiveIntegerField(null=True)),
                ('money_owed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'permissions': (('is_manager', 'Manager User'), ('is_provider', 'provider User'), ('is_applicant', 'applicant User')),
            },
        ),
        migrations.CreateModel(
            name='QuotationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_authorized', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Provider')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(to='main.Provider'),
        ),
    ]
