# Generated by Django 2.1 on 2018-09-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180831_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetails',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='quotationdetails',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
