# Generated by Django 2.1 on 2018-09-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180907_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetails',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/%Y/%m/%d'),
        ),
    ]
